[client]
showSidebarNavigation = false,
toolbarMode = "viewer"

[theme]
base="Dark",
primaryColor="#FF4B4B",
backgroundColor = "#FFFFFF",
secondaryBackgroundColor = "#F0F2F6",
textColor = "#333333",
font = "sans serif",

