[general]
GOOGLE_CREDENTIALS = "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicmljaC1pbXBs
ZW1lbnQtNDIzNjEwLWIwIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZWYzZmRmODY4N2VhYTRlZTA5
ODIzYmY0ODdmYTNlYjQzYmE5OWU5NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJ
VkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0Fn
RUFBb0lCQVFEMUU0V0hnZERwbUJkbVxuaGpobjErdnlqVTBMTTdNL1BrQzJPZDBhaU1lNStHdXN5
RmpkTGIyM2YxZGpSdXhycG1mMXVvWFp6d2g0Tk0xZVxuSFNtdXJtNURtZDkvS3dPWFB4NlNRQ2lN
eXBIRytYVWcxdnZkMmFveUpLQnYzQkZIbWZHdkVCSENZSnR6UGVuSFxudjdhUVJnREsrNG8yMkpM
M1M4bkcrZ3c3cEo2VW5sRmVtVCtuTDg4ZThKTXZqcmRLMzVtQXpQWDFIU2xPdFNQQVxua3VDTjMy
RTFURWwvSDJPMXJZRUwrd0tQNjM5UlJqMDRPc0xIOFR0Sy9zalc3R09VeHBtbDNvdDNsYkdUaTlu
ZVxuRTY3Y0xTR1lOc2p1aGROcGYwVTg0aTlCM29yUlFyc3BYa2NWRUFFOFpzN0R2WGpsd2lIekh6
aUV3blVPcEJ5ZFxuQm11L1pMOFpBZ01CQUFFQ2dnRUFFVUdISU9Qd21Fb0h0OFhTbWVrM3FWUHVy
VSsrR3NGZzRCUFI4Q2phVzB0VlxuRll6anlPc01GU3dIdEt0TlFVVXR3NzBXNkordHVuMEpTc3Vs
NERGUy9UcUw1SkhjUmwyQTR3NVdiSmRrelV4S1xuUlg0dHJORERMWldyb0VTd0NNa2JuZFoxVWFq
b3VTUU9YbXl1eDVqT1BIeWFua01Ba2g0SmZwT2pvZDEwOXdUTlxuY2pzSS9XYWgxMG5GQ2JFaXV0
QjRyTlBJdE9JbkM5L1k5RHluUFUrZUxvT0lhV1NlRmVobkY4aVdTOTM1YXZjdlxudlRJeEgrQk9J
aWJ2dWRQay8vb0ZUM2ROZWc1Qzl4SFYyMHM2ZEd5WjQxVmQ0dVNxUGJDa1orTnQzU3MrUGJ1ZFxu
Z091THZBUTFGWnRZbTY1c3ppUU5saVRJd2dNblJPdU5QQ3U4eWtvdUV3S0JnUUQ5c2taTmQvU2Q4
SU01a0NtWVxuZTliNTZNdDB1SU9EVy9NYlpVNTlYSm4rbW1SczhUNVRPSVgvaEZRVDNkNWZta043
RkljNVRDWnVmY0VvZG8weFxueDBNRjNJYzMrdzBCd2JGRzhLNFE5M0R1bUhFcXY3TkZnQXE3aURH
MWZqV3NUd1dlN0pvM1Bzemo3MUwxUjF3QlxuSGlkMDhBVThHS0RlaVlGa09zK3ZPQUlDcndLQmdR
RDNUVFdPL3FCWGIvZXFKbXJJaTFjWXZWZ29reC8yY2NCWlxub0VaaXpsem9iOURRbWx3a1dTMk5q
dUhDKzJDUzNJSDAyaXVFUTlIS0pDUmRBeW5PcE81aUJpcHJvSDlyd2lvd1xuSFhhYlZVU0xpMlRv
cFpHY1dCVmNmWGlLWDlLQ2gxbkFUenl3VFRWdkI0cGtncXp5REVyL2NNSnl4RW9nVWxRUFxuQnQ4
NUlSMXN0d0tCZ1FEcFpZckNHSnJHZHcveTlFc2dTc1pqVWlWanM2RGlSOFNucnBNQVNDSXdscy9Q
WGo0dFxuaC9IWE9tR3ppVW5kQUdvV29MTXJKb0N3NUNiQldCZmI5T3NYU0dScVB5QWZQcGdlb0t3
elZjSGk4QUlsQndvaFxuNVlONk5ma3RkUGhpRnEwZ0lhSmJNdjZDc0puTXFDTGZzR015ZE9NTC84
aDRFMThqMit0WDB4b2Vad0tCZ0I4Q1xucFlhcTB6eGpvL0RJSkhmRlVVU2U2YUVjNGRNcmJHMVF0
Y0xLRWNocnpRbDdjYloxSUVzeDhZbGJzRDU2UENtUlxuK2diNTRpS3c2WVpvVVNQQ2Rzbi83KzNU
RUdkWXo2Vjg3RlNLR3JCTTZIaHIycGg2U3lOdjhGK1pxSElKdXUxc1xuZ2pXeFdOUDFaQnM2YjZs
aWRUMFd6S3RMaGVnTHF0Sy9qOXBBRnNwOUFvR0JBTmhpRTFBVVJ4VTErZnZ5a093N1xuNGp2b1RO
RnJuQWMyUEhsUzdwMHdhcTRBa2xteG9ldW5vd29lekpRM3JoSTBRTldsbHJLR1MxbDYxS1YrR29O
a1xuakpWbmZiUWVXNTdRaldJZ2R4cE5hUlBRdkxYcHBZS1VteE83cGQvZVFKSkZvbDlEdGVFM2FC
MmUyUzJ3MlBtZ1xuc1I0VVRmNTgrZ3FjaHArWUxBWnh0bUt4XG4tLS0tLUVORCBQUklWQVRFIEtF
WS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAic3Ryb25nd29tYW5AcmljaC1pbXBsZW1lbnQt
NDIzNjEwLWIwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExNTUw
NzgyODM0ODA1MzQ1MjA0NSIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xl
LmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2ds
ZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBz
Oi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2Nl
cnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1
MDkvc3Ryb25nd29tYW4lNDByaWNoLWltcGxlbWVudC00MjM2MTAtYjAuaWFtLmdzZXJ2aWNlYWNj
b3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
